# Generated by Django 4.2.3 on 2023-08-16 17:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checkout", "0002_order_county_alter_order_country_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="original_bag",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="order",
            name="stripe_pid",
            field=models.CharField(default="", max_length=254),
        ),
    ]
