# Generated by Django 4.2.3 on 2023-08-17 19:40

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):
    dependencies = [
        ("checkout", "0003_order_original_bag_order_stripe_pid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="country",
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
