# Generated by Django 4.2.3 on 2023-08-22 12:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testimonials", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="testimonial",
            name="approved",
            field=models.BooleanField(default=False),
        ),
    ]
