# Generated by Django 4.2.3 on 2023-07-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='label_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
