# Generated by Django 4.2.3 on 2023-07-30 16:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_alter_product_description_alter_product_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="additionalimages",
            options={"verbose_name_plural": "Additional Images"},
        ),
        migrations.AlterField(
            model_name="product",
            name="uploaded_on",
            field=models.DateTimeField(),
        ),
    ]
