# Generated by Django 4.2.3 on 2023-08-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_alter_additionalimages_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="fragrance_categories",
            field=models.ManyToManyField(blank=True, to="products.fragrancecategory"),
        ),
    ]
