# Generated by Django 4.2.3 on 2023-08-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_alter_product_fragrance_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=254, unique=True),
        ),
    ]
